[package]
name = "rusty_store_management_system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "2.0.2"
tui = "0.19"
crossterm = "0.27.0"
serde_json = "1.0.108"
